// 英文目录：内容 4。键是中文原文（逐字），值是英文。占位符 {名字} 两边一致。
export default {
  // ── 通用标点 / 短词（与别的目录一致）──
  '；': '; ',
  '、': ', ',
  '（无）': '(none)',
  '系统': 'System',
  '请选一条：': 'Please pick one:',
  '没有这个项目：{id}': 'No such project: {id}',
  '依赖 {deps}': 'Depends on {deps}',

  // ── src/core/revision.mjs ──
  '触及宪法层（方案要改 {fields}）—— agent 无权自行改宪法块': 'Touches the contract (the plan changes {fields}) — the agent may not change the contract on its own',
  '方案带了 constitution_patch 但形状不对（没有一个字段会被应用）—— 这本身就该人来看一眼，不能当成"没填"放过去': 'The plan has a constitution_patch in the wrong shape (no field in it would be applied) — a person should look at that; it can\'t be let through as if it were empty',
  '要重来的已完成工作占比 {ratio}% > 阈值 {threshold}%（作废 {discarded} + 重做 {redone} / 已完成 {done}，合计 {affected} ≥ 下限 {floor}）': 'Completed work that has to be redone is {ratio}% > threshold {threshold}% (discarded {discarded} + redone {redone} / completed {done}; total {affected} ≥ floor {floor})',
  '人发来的修正：': 'The correction that was sent:',
  '重规划器给出的方案：': 'The replanner\'s plan:',
  '为什么要你批：{gate}': 'Why this needs your approval: {gate}',
  [`这条问题由**状态机**生成、强制定为 Ⅲ 级（触及安全边界或宪法层的操作由 harness 定级，不是模型自评）。

请选一条。发给了几个人的，可能要几个人都批才生效 —— 还差谁，看这条事项上方的「待…答复」。负责人在任务页「计划变更」卡片上点批准 / 驳回，就等于在这里答了一次，不用再答：
(A) 批准：回「A」—— 够数后变更生效，任务接着跑
(B) 驳回：回「B：理由」—— 计划原样不动，修正记为已处理；要换个改法，再发一条修正
(C) 先看细节：任务页的「计划变更」卡片（改哪几步、新增哪几步、范围怎么变）
(D) 批准，但留一句保留意见：回「A」，另起一行写「保留：……」。
　　**它不挡任何东西**：这份变更照样全部生效，效果与 (A) 一模一样。它只把你那句话留在项目的
　　约定清单上、标成〔保留意见〕，让下一个碰这一处的人看得到。
　　要**挡住**里面某一条，只能 (B) 驳回并说清哪一条不要，让它重出一版 —— 这份方案不能只批一半。`]: `This item was generated by the **state machine** and fixed at level Ⅲ (operations that touch a safety boundary or the contract are leveled by the harness, not self-assessed by the model).

Pick one. If it went to several people, several of them may need to approve before it takes effect — the "Waiting for … to reply" line above this item shows who is still missing. The owner clicking Approve / Reject on the "Plan change" card on the task page counts as answering here once; no need to answer again:
(A) Approve: reply "A" — once enough people approve, the change takes effect and the task continues
(B) Reject: reply "B: <reason>" — the plan stays as it is and the correction is marked handled; to try a different change, send another correction
(C) Look at the details first: the "Plan change" card on the task page (which steps change, which are added, how the scope changes)
(D) Approve, but leave a reservation: reply "A", and on a new line write "Reservation: …".
　　**It does not block anything**: the change still takes full effect, exactly like (A). It only keeps what you said on the project's
　　agreed-decisions list, marked [reservation], so the next person who touches this part can see it.
　　To **block** one item in it, you can only (B) reject and say which one you don't want, so a new version is produced — this plan can't be half-approved.`,
  '没有这份提案：{id}': 'No such proposal: {id}',
  '提案 {id} 状态是 {status}，不能重复应用': 'Proposal {id} is {status}; it can\'t be applied again',
  '提案 {id} 状态是 {status}': 'Proposal {id} is {status}',
  '节点因修正 {msg} 作废': 'Step discarded because of correction {msg}',
  '产物处置：{what}': 'What happens to the output: {what}',
  '（未完成，无产物）': '(not finished, no output)',
  '⚠️ 产物**没有被删除**：git 历史里仍然在，这条记录是为了让人知道那条路径不再算数。': '⚠️ The output was **not deleted**: it is still in the git history. This record is here so people know that path no longer counts.',
  [`提案 {id} 的 constitution_patch 里没有任何会被应用的字段（收到 {kind}）。
继续下去会把宪法升一版而内容一字未改 —— 那比直接报错坏得多：
人以为批准的改动生效了，审计轨也说生效了，其实什么都没发生。`]: `Proposal {id} has a constitution_patch with no field that would be applied (got {kind}).
Going on would bump the contract version without changing a word — much worse than failing here:
people would think the approved change took effect, the audit trail would say so too, and nothing would actually have happened.`,
  '宪法块修订至 v{version}': 'Contract revised to v{version}',
  '因修正 {msg}：{why}': 'Because of correction {msg}: {why}',
  '已由修正提案 {id} 处理': 'Handled by correction proposal {id}',
  '批准计划变更时的保留意见': 'Reservation left when approving a plan change',
  '修正提案 {id} 被驳回': 'Correction proposal {id} was rejected',
  '影响：无关 {unaffected} 个｜需修改 {needsChange} 个｜**作废 {obsolete} 个**｜新增 {added} 个': 'Impact: {unaffected} unaffected | {needsChange} to change | **{obsolete} discarded** | {added} new',
  '受影响的已完成工作（按花费算，这是确认门的口径）：': 'Completed work affected (measured by cost — this is what the approval gate uses):',
  '[作废] {title}　{usd}': '[discarded] {title}　{usd}',
  '[重做] {title}　{usd}': '[redo] {title}　{usd}',
  '作废 {discarded} + 重做 {redone} / 已完成 {done}　= {ratio}%（阈值 {threshold}%，金额下限 {floor}）': 'discarded {discarded} + redone {redone} / completed {done}　= {ratio}% (threshold {threshold}%, amount floor {floor})',
  '占比过了阈值，但受影响的金额 {affected} 不到下限，按"不值得为这点钱打断人"处理：方案直接生效，这份 diff 就是通知。': 'The share is over the threshold, but the amount affected ({affected}) is under the floor, so this is treated as "not worth interrupting anyone for": the plan takes effect directly and this diff is the notice.',
  '改了规格的未完成节点（没花过钱，所以不进上面的比例，但计划确实变了）：': 'Unfinished steps whose spec changed (no money spent on them, so they are not in the share above — but the plan did change):',
  '改了 {what}': 'changed {what}',
  '（没说改什么）': '(did not say what)',
  '依赖边重挂 {n} 处（旧边 supersede，不删）：': 'Dependencies rewired in {n} places (old edges are superseded, not deleted):',
  '新增 {n} 个节点：': '{n} new steps:',
  '部分抢救 {n} 个 —— **不计入上面的比例**："留了多少"没法机械判定，算全丢会高估、算没丢会低估，两边都是编数字。自己看：': '{n} partly salvaged — **not counted in the share above**: "how much was kept" can\'t be judged mechanically; counting it all as lost overstates it, counting none as lost understates it, and either way the number would be made up. Look for yourself:',
  '**宪法块改动**（这是要你批的主要理由）：': '**Contract changes** (the main reason this needs your approval):',
  '{field}：{value}': '{field}: {value}',
  '理由：{why}': 'Reason: {why}',
  '在事项里驳回（未写理由）': 'Rejected in the item (no reason given)',

  // ── src/core/decision-check.mjs ──
  '（模型没给理由）': '(the model gave no reason)',
  '（系统）': '(system)',
  '新任务描述': 'new task description',
  '变更消息': 'change message',
  '对问题的答复': 'answer to a question',
  ' · 管理员': ' · admin',
  '（{i}）': '({i}) ',
  '（{day} 由 {who} 定下，是批准过的契约里的条款）': ' (decided by {who} on {day}; a clause of an approved contract)',
  '（{day} 由 {who} 定下）': ' (decided by {who} on {day})',
  '为什么对不上：{why}': 'Why they don\'t fit: {why}',
  '你这次说的，会推翻你自己先前定下的一条决定。': 'What you just said would overturn a decision you made earlier yourself.',
  '你这次说的，会推翻你自己先前定下的{n} 条决定。': 'What you just said would overturn {n} decisions you made earlier yourself.',
  '这次的{entry}，和一条仍然有效的旧决定对不上。': 'This {entry} doesn\'t fit with an earlier decision that is still in force.',
  '这次的{entry}，和 {n} 条仍然有效的旧决定对不上。': 'This {entry} doesn\'t fit with {n} earlier decisions that are still in force.',
  '这次说的（{who}）：{quote}': 'What was said this time ({who}): {quote}',
  '（见本任务的最新消息）': '(see the latest message on this task)',
  '旧决定：': 'Earlier decision:',
  '被推翻的 {n} 条旧决定：': 'The {n} earlier decisions it overturns:',
  '其中有契约里的条款 —— 契约是你批准过的，改它只能由你来定。': 'Some of them are contract clauses — you approved the contract, so only you can decide to change it.',
  '定下这些决定的人已经停用，所以这条交给你。': 'The people who made these decisions have been deactivated, so this comes to you.',
  '先由 {by} 与{others} 商量；谈不拢或超时转项目负责人裁定。': '{by} and {others} talk it over first; if they can\'t agree or time runs out, the project owner decides.',
  '请选一条（一次选定，上面 {n} 条一起处理）：': 'Please pick one (one choice settles all {n} above):',
  '(A) **以新为准** —— 上面那条旧决定就此作废：回「以新为准」': '(A) **Go with the new** — the earlier decision above is voided: reply "A"',
  '(A) **以新为准** —— 上面那些旧决定就此作废：回「以新为准」': '(A) **Go with the new** — the earlier decisions above are voided: reply "A"',
  '(B) 以旧为准 —— 这次的说法不算数，照旧决定执行：回「以旧为准」': '(B) Keep the old — what was said this time doesn\'t count; follow the earlier decision: reply "B"',
  '(C) 其实不冲突 —— 都能同时成立：回「不冲突：」再写一句为什么': '(C) Not actually a conflict — both can hold: reply "Not a conflict:" and say why in a sentence',
  '系统不替你判谁对。选 (A) 之后，它会在清单里标成"已作废"，并记下是被这次的说法取代的。': 'The system doesn\'t decide who is right. After (A), it is marked "voided" on the list, with a note that it was replaced by what was said this time.',
  '系统不替你判谁对。选 (A) 之后，它们会在清单里标成"已作废"，并记下是被这次的说法取代的。': 'The system doesn\'t decide who is right. After (A), they are marked "voided" on the list, with a note that they were replaced by what was said this time.',
  '写着这条的任务说明原文不改，但那个任务之后执行时会照新的说法做，不会为这一条再来问你。': 'The task description that contains it stays as written, but that task will follow the new wording from now on and won\'t ask you about this again.',
  '如果只想作废其中一部分，回 (C) 并说明哪几条该留，然后对该留的那几条不必再管；要改的那几条另提一次。': 'To void only some of them, reply (C) and say which ones should stay; you then don\'t need to do anything about those, and you raise the ones to change again separately.',
  [`⚠ 这次说的是一条要改计划的修正，它**在你选定之前不会执行**，这个任务也先停着。
选 (A)，修正照做；选 (B)，修正里与旧决定相冲的那部分不执行，其余照做。
旧决定在你选定之前仍然留在"已定的约定"清单上（标成"正在被争议"）。`]: `⚠ What was said is a correction that changes the plan. It **won't run until you choose**, and this task is paused meanwhile.
With (A) the correction goes ahead; with (B) the part of it that conflicts with the earlier decision is dropped and the rest goes ahead.
Until you choose, the earlier decision stays on the "agreed decisions" list (marked "disputed").`,
  [`⚠ 这条事项**没有拦住任何事**：这次说的已经生效了，旧决定在你选定之前也仍然留在"已定的约定"清单上
（它们会被标成"正在被争议"）。在你选之前，两边都在 —— 所以别拖。`]: `⚠ This item **doesn't hold anything up**: what was said has already taken effect, and until you choose, the earlier decisions also stay on the "agreed decisions" list
(marked "disputed"). Until you choose, both are in force — so don't leave it.`,
  '路由表解析出零个收件人，兜底改派给项目负责人': 'The routing table resolved to no recipients, so this was sent to the project owner as a fallback',
  '这几条决定落在他们的范围上，按路由表该让他们知道': 'These decisions fall in their area, so per the routing table they should know',
  '由事项 {id} 判定以新为准': 'Item {id} decided to go with the new',

  // ── src/core/choices.mjs ──
  '依赖、构建或仓库结构上': 'about dependencies, the build or the repository layout',
  '规格没写、界面或行为上': 'about the interface or behavior, which the spec didn\'t cover',
  '任务「{title}」做的时候，{what}有 {n} 件事是 AI 自己定的（规格里没写，它查过之后自己选了一个）。下面是它交接时的原话，系统原样摘出来，没有改写：': 'While working on task "{title}", the AI decided {n} things {what} on its own (the spec didn\'t say; it looked into it and picked one). Below is what it said at handover, quoted by the system without rewording:',
  '它的依据：{basis}': 'Its basis: {basis}',
  '……另有 {n} 件，见任务页「活动」里的"系统代为决定"。': '…and {n} more; see "Decided by the system" under Activity on the task page.',
  '这条不影响任务照常签收、合并。怎么答：': 'This doesn\'t hold up sign-off or merging. How to answer:',
  '- 都行：回「A」（代表上面几件全部同意，不是选第几条）。这几件记进项目的约定清单，以后的任务照着来。': '- All fine: reply "A" (meaning you agree with all of the above, not picking one). They go on the project\'s agreed-decisions list and later tasks follow them.',
  '- 有要改的：直接写改成什么（比如"2 改成：高 / 中 / 低 倒过来显示"）。系统替你「添加任务」去改 —— 这个任务照常签收、合并，改动放在后面单独做、单独批。': '- Something to change: just write what it should be (e.g. "2: show high / medium / low in reverse order"). The system will "Add a task" for you to make the change — this task is signed off and merged as usual, and the change is done and approved separately afterwards.',
  '- 只想补一句说明、不要求改：以「说明：」开头写。只记下来给后面的人看，不会引出任何改动。': '- Just a note, no change wanted: start with "Note:". It is only recorded for whoever comes later and won\'t lead to any change.',
  '- 不答：到期按"沿用 AI 的选择"了结。': '- No answer: when it times out it is closed as "keep the AI\'s choices".',
  '沿用 AI 的选择，不改': 'Keep the AI\'s choices, no change',
  '{n} 件 AI 自选的事交给结构那一行的人过目': '{n} things the AI decided on its own sent for review to the people on the structure row',
  '{n} 件 AI 自选的事交给规格那一行的人过目': '{n} things the AI decided on its own sent for review to the people on the spec row',
  '{who}对 AI 定的事补了一句说明：{note}': '{who} added a note on what the AI decided: {note}',
  '（AI 定的，{who}过目同意）': ' (decided by the AI; reviewed and agreed by {who})',
  '{who}同意了 AI 定的 {n} 件事': '{who} agreed with the {n} things the AI decided',
  '「{title}」里 AI 替人定的几件事，{who}要改：': '{who} wants to change some of the things the AI decided in "{title}":',
  '—— 当时 AI 定的（系统原样附上）——': '— What the AI decided at the time (attached by the system as is) —',
  '{who}要改 AI 定的事；任务已合并，替{who}添加了任务（排队）': '{who} wants to change what the AI decided; the task was already merged, so a task was added for {who} (queued)',
  '{who}要改 AI 定的事；任务已合并，替{who}添加了任务': '{who} wants to change what the AI decided; the task was already merged, so a task was added for {who}',
  '{who}对 AI 替人定的事要改：': '{who} wants to change what the AI decided:',
  '—— 系统附（不由模型生成）：当时 AI 定的 ——': '— Attached by the system (not model-generated): what the AI decided at the time —',

  // ── src/core/egress.mjs ──
  '域名是空的': 'The domain is empty',
  '「{h}」不是一个域名：只写域名本身，不要带 https://、端口或路径': '"{h}" is not a domain: write just the domain, without https://, a port or a path',
  '「{h}」是 IP 地址：只允许域名': '"{h}" is an IP address: only domains are allowed',
  '「{h}」：通配只能写在最前面，形如 *.example.com': '"{h}": a wildcard can only come first, as in *.example.com',
  '「{h}」不是合法的域名': '"{h}" is not a valid domain',
  '「{h}」只有一段：要写完整域名，例如 docs.example.com': '"{h}" has only one label: write the full domain, e.g. docs.example.com',
  '「{h}」是本机或内网地址：不允许经代理访问': '"{h}" is a local or internal address: it can\'t be reached through the proxy',
  '「{h}」：通配的后缀至少要两段（*.example.com 可以，*.com 不行）': '"{h}": a wildcard suffix needs at least two labels (*.example.com is fine, *.com is not)',
  '「{k}」不是合法的环境变量名': '"{k}" is not a valid environment variable name',
  '「{k}」是沙箱自己的出网 / 证书 / 身份配置，不能在这里改': '"{k}" is part of the sandbox\'s own network / certificate / identity setup and can\'t be changed here',
  '「{k}」的值是空的': 'The value of "{k}" is empty',
  '只有管理员能改联网目录：往目录里加一个源，等于给所有项目多开一个可选的出口': 'Only an admin can change the network catalog: adding a source gives every project one more way out that it can choose',
  '要给这个源起个名字（例如「清华 PyPI 镜像」）': 'Give this source a name (e.g. "Tsinghua PyPI mirror")',
  '类型只能是 {kinds}': 'The type must be one of {kinds}',
  '至少要有一个域名': 'At least one domain is required',
  '联网目录里没有这个源：{id}': 'No such source in the network catalog: {id}',
  '内置的源不能删；不想用就在项目联网里不勾它': 'Built-in sources can\'t be deleted; if you don\'t want one, leave it unchecked in the project\'s network settings',
  '新项目默认放行（管理员在「设置 → 联网目录」里设的）': 'Allowed by default for new projects (set by an admin under "Settings → Network catalog")',
  '只有项目负责人能改项目联网': 'Only the project owner can change the project\'s network access',
  '联网目录里没有：{ids}': 'Not in the network catalog: {ids}',
  '联网目录里没有：{ids}（可选：{all}）': 'Not in the network catalog: {ids} (available: {all})',
  '经任务 {id} 放行': 'Allowed via task {id}',
  '「{want}」既不是联网目录里的源，也不是合法的域名（目录里有：{all}）': '"{want}" is neither a source in the network catalog nor a valid domain (the catalog has: {all})',
  '⚠️ 审计轨里**没有被拦记录**。本任务若完全断网，这是正常的 —— 请求根本到不了代理。': '⚠️ The audit trail has **no blocked requests**. That is normal if this task has no network access at all — requests never reach the proxy.',
  '✅ 与被拦记录对得上：{hosts}': '✅ Matches the blocked requests: {hosts}',
  '⚠️ 还有不属于它的被拦域：{hosts}': '⚠️ Other blocked domains that it doesn\'t cover: {hosts}',
  '⚠️ **对不上**：它请求「{name}」，但被拦的是 {hosts}　←　放行它不会让这些通，先弄清为什么': '⚠️ **Doesn\'t match**: it asks for "{name}", but what was blocked is {hosts}　←　allowing it won\'t let these through; find out why first',
  '被拦记录：{hosts}': 'Blocked requests: {hosts}',
  '本项目的联网设置（项目下所有任务都能用）': 'this project\'s network settings (every task in the project can use it)',
  '本任务的放行名单': 'this task\'s allow list',
  '(A) 放行「{name}」（{hosts}，只读）—— 加进{scope}': '(A) Allow "{name}" ({hosts}, read-only) — added to {scope}',
  '(A) 放行「{name}」（{hosts}）—— 加进{scope}': '(A) Allow "{name}" ({hosts}) — added to {scope}',
  '(B) 把 {host} 加进联网目录（作为只读的信息源）并放行 —— 只有管理员能选：它扩大的是整个部署可选的出口': '(B) Add {host} to the network catalog (as a read-only information source) and allow it — only an admin can choose this: it widens the ways out available to the whole deployment',
  '(C) 不放行 —— 让它改用离线方式完成': '(C) Don\'t allow — have it finish offline instead',
  '请求放行「{name}」': 'Asks to allow "{name}"',
  '请求访问 {host}（不在联网目录里）': 'Asks to access {host} (not in the network catalog)',
  'agent 给的理由：{why}': 'The agent\'s reason: {why}',
  '放行意味着沙箱里的代码可以连上这些地址，并向它们发送数据。': 'Allowing it means code in the sandbox can connect to these addresses and send data to them.',
  '当前已放行：{list}': 'Currently allowed: {list}',
  '（无，完全断网）': '(none — no network access at all)',
  '请选一条（回复字母即可，选定后立即生效）：': 'Please pick one (just reply with the letter; it takes effect immediately):',
  '（{host} 不在联网目录里，所以没有「直接放行」这一项；不是管理员的话，要放行请找管理员）': '({host} is not in the network catalog, so there is no "just allow" option; if you are not an admin, ask an admin to allow it)',
  '事项 {id} 选 (A)': 'Item {id}: chose (A)',
  '由事项 {id} 加入（agent 请求时说：{why}）': 'Added via item {id} (the agent said when asking: {why})',
  '事项 {id} 选 (B)': 'Item {id}: chose (B)',
  '反复出现的域 = 白名单漏了哪个生态的候选': 'Domains that keep showing up = candidates for an ecosystem missing from the allow list',

  // ── src/core/decisions.mjs ──
  '〔答复〕': '[answer]',
  '〔契约〕': '[contract]',
  '〔计划变更〕': '[plan change]',
  '〔项目目标〕': '[project goal]',
  '被 {id} 取代': 'Replaced by {id}',
  '决定不存在：{id}': 'No such decision: {id}',
  '批准时的保留意见': 'Reservation left at approval',
  '{title}｜': '{title} | ',
  '〔批准过的草案约束〕': '[approved draft constraint]',
  '〔规格〕出处：“{quote}”': '[spec] source: “{quote}”',
  '〔规划器假设〕{assumption}': '[planner assumption] {assumption}',
  '{pre}行为规则': '{pre}Behavior rule',
  '（{src}）': ' ({src})',
  '{pre}改动范围': '{pre}Scope of changes',
  '{pre}验收命令': '{pre}Acceptance command',
  '（改了本任务契约的{fields}）': ' (changed this task\'s contract: {fields})',
  '计划变更 {id}': 'Plan change {id}',
  '本任务契约的{field}': 'This task\'s contract: {field}',
  '项目目标与完成定义': 'Project goal and definition of done',
  '目标：{goal}\n完成定义：{done}': 'Goal: {goal}\nDefinition of done: {done}',
};
