// 英文目录：内容 5。键是中文原文（逐字），值是英文。占位符 {名字} 两边一致。
export default {
  // src/agent/approval.mjs —— 判读说明（describeReading）
  '如果现在点「答复」，系统会理解为': 'If you click “Answer” now, the system will read this as',
  '已提交，系统理解为': 'Submitted; the system read this as',
  '已经达成': 'Already done',
  '{head}：已经达成（E）。这一版提的任务都不做，项目按已达成处理（填了项目级验收命令的，系统先跑一遍，过了才算）；之后可以交付。':
    '{head}: already done (E). None of the tasks proposed in this version will be done, and the project is treated as done (if a project acceptance command is set, the system runs it first and it only counts if it passes); after that you can deliver.',
  '确认达成': "Confirm it's done",
  '{head}：确认达成（A）。填了项目级验收命令的，系统先跑一遍，过了才算达成；之后可以交付。':
    "{head}: confirm it's done (A). If a project acceptance command is set, the system runs it first and the project only counts as done if it passes; after that you can deliver.",
  '{head}：批准（A）。这一版方案照原样生效。': '{head}: approve (A). This version of the plan takes effect as is.',
  '「{resv}」记成保留意见：不挡任何东西，只留在项目的约定清单上。': '"{resv}" is recorded as a reservation: it doesn\'t block anything, it just stays in the project\'s agreed decisions.',
  '先放着': 'Set it aside',
  '放弃': 'Drop it',
  '{head}：先放着（C）。项目不标达成、转为停滞，等人添加任务、宣布达成或中止。{extra}':
    '{head}: set it aside (C). The project is not marked done; it becomes stalled until someone adds tasks, declares it done, or aborts it.{extra}',
  '只是不要这些任务、项目其实已经达成：回「E」。': ' If you just don\'t want these tasks and the project is actually done: reply "E".',
  '{head}：放弃（C）。这一版方案作废，不再出新版。': '{head}: drop it (C). This version of the plan is discarded and no new version will be drafted.',
  '还差东西': 'Something is missing',
  '要改': 'Needs changes',
  '{head}：{what} —— 你写的这段话会原样交给 AI，按它出下一版方案，再来问你（要等 AI 重写一版，通常几分钟，花一次模型调用的钱）。':
    '{head}: {what}. What you wrote goes to the AI verbatim; it drafts the next version of the plan from it and asks you again (the AI needs to rewrite it, which usually takes a few minutes and costs one model call).',
  '还差东西（B）': 'something is missing (B)',
  '要改（B）': 'needs changes (B)',
  '你以「{lead}」开头，但后面有「{hedge}」这样要改的话，所以不算批准。': 'You started with "{lead}", but what follows asks for a change ("{hedge}"), so it doesn\'t count as an approval.',
  '你以「{lead}」开头，但后面还接着写了话，系统分不清是批准还是要改，按"要改"算。': 'You started with "{lead}" but kept writing after it; the system can\'t tell whether that is an approval or a change request, so it counts as "needs changes".',
  '只想批准：只回「A」；批准但想留一句话：先回 A，另起一行写「保留：…」（不挡任何东西）。': ' To just approve: reply only "A". To approve with a note: reply A, then on a new line write "Reservation: …" (it doesn\'t block anything).',

  // src/agent/approval.mjs —— 【先确认一下】事项（confirmBeforeRevising）
  '上一版': 'the previous version',
  '你对方案连着两次的答复都以「{lead}」开头、后面又写了话，两次系统都没法当成批准 —— 上一次已经按"要改"多出了一版。这一次先不出新版，问清楚再动。':
    'Your last two replies to the plan both started with "{lead}" and then went on, so neither could be taken as an approval; last time that already produced an extra version as "needs changes". This time no new version is drafted until this is cleared up.',
  '（这条事项本身是系统按规则直接生成的，不是 AI 写的。）': '(This item was generated by the system from a fixed rule, not written by the AI.)',
  '你前一条答复写的：': 'Your previous reply said:',
  '方案本身见上一条事项（{v}）。怎么答：': 'The plan itself is in the previous item ({v}). How to reply:',
  '- 确认达成：只回「A」。': '- Confirm it\'s done: reply only "A".',
  '- 就按 {v} 批准：只回「A」。想留一句话，另起一行写「保留：…」—— 不挡任何东西，只记在约定清单上。':
    '- Approve {v} as is: reply only "A". To add a note, write "Reservation: …" on a new line — it doesn\'t block anything, it is just recorded in the agreed decisions.',
  '- {what}：直接写要改什么（别用「A」开头）；你前一条答复的原话会和这次写的一起交给 AI，按它出下一版。这条确认只问一次，这次的答复系统照常判读。':
    '- {what}: write what to change (don\'t start with "A"); your previous reply and this one go to the AI together, and it drafts the next version from them. This check is asked only once; this reply is read as usual.',
  '- 先放着：回「C」。': '- Set it aside: reply "C".',
  '- 放弃这份方案：回「C」。': '- Drop this plan: reply "C".',

  // src/agent/elicitor.mjs —— 【宪法块草案】
  '标题：{v}': 'Title: {v}',
  '可动路径（判据）：{v}': 'Allowed paths (what is enforced): {v}',
  '完成定义：{v}': 'Definition of done: {v}',
  '（没给 —— 见说明）': '(none given — see notes)',
  '批准后会自动规划并开跑。请回复：': 'Once approved, it is planned and started automatically. Please reply:',
  '(A) 批准 —— 回 "A" 或 "批准"': '(A) Approve — reply "A" or "approve"',
  '(B) 要改 —— 直接写要改什么，会出下一版': '(B) Needs changes — write what to change, and a new version will be drafted',
  '(C) 放弃 —— 回 "C" 或 "放弃"': '(C) Drop it — reply "C" or "drop it"',
  '(D) 批准，但留一句保留意见 —— **它不挡任何东西**：这一批照样全部生效，效果与 (A) 一模一样。它只把你那句话留在项目的约定清单上、标成〔保留意见〕，让下一个碰这一处的人看得到。要**挡住**其中某一条，只能 (B) 说清哪一条不要、让它重出一版。写法：先回 A，**另起一行**写「保留：…」。':
    '(D) Approve, with a reservation — **it doesn\'t block anything**: everything takes effect exactly as with (A). It only records your note in the project\'s agreed decisions, tagged [reservation], so the next person to touch this sees it. To **block** a specific point, use (B) and say which one you don\'t want, so a new version is drafted. How: reply A, then **on a new line** write "Reservation: …".',
  '想法不能为空': "The idea can't be empty",
  '这个任务不是从想法开始的（没有 draft.idea），不需要追问': "This task didn't start from an idea (no draft.idea), so there is nothing to ask about",
  '草案等人批，但找不到答复': 'The draft is waiting for approval, but no reply was found',
  '批准草案 v{version} 时的保留意见': 'Reservation when approving draft v{version}',
  '追问器 {n} 次都没给出合法动作：{errs}': 'The drafting assistant gave no valid action in {n} attempts: {errs}',
  '（为什么问：{why}）': '(Why this is asked: {why})',

  // src/agent/project-planner.mjs —— 【项目契约草案】
  '规划文本为空': 'The plan text is empty',
  '项目规划：{title}': 'Project planning: {title}',
  '同时最多开着 {n} 个任务：平时一次只做一个，只有开着的任务全都在等人（等你答题、等你签收）时，系统才会让独立的下一个先跑起来。':
    'Up to {n} tasks can be open at once: normally one runs at a time, and only when every open task is waiting on people (for your answers or sign-off) does the system start the next independent one.',
  '同一时间只执行一个任务。': 'Only one task runs at a time.',
  '项目：{v}': 'Project: {v}',
  '   依赖：{v}': '   Depends on: {v}',
  '   目标：{v}': '   Goal: {v}',
  '   范围：{v}': '   Scope: {v}',
  '   可动路径（判据）：{v}': '   Allowed paths (what is enforced): {v}',
  '   完成定义：{v}': '   Definition of done: {v}',
  '   规则：{v}': '   Rules: {v}',
  '   约束：{v}': '   Constraints: {v}',
  '   验收命令：{v}{extra}': '   Acceptance command: {v}{extra}',
  '（开工时系统会再累加当时已合并的全部任务的验收命令）': ' (when it starts, the system also adds the acceptance commands of every task merged by then)',
  'T{n} · {rule}（{why}）': 'T{n} · {rule} ({why})',
  '⚠ 规划器假设（规格没写、规划器定的，共 {n} 条；批准即认可，不同意就在反馈里改）：{list}':
    '⚠ Planner assumptions (not in the spec, decided by the planner; {n} in total; approving accepts them, so if you disagree, change them in your feedback):{list}',
  '规划器假设：无（每条规则都引了规格原文）': 'Planner assumptions: none (every rule quotes the spec)',
  '规划器说明：{v}': 'Planner notes: {v}',
  '每个任务的硬上限：累计运行时长 {h} h（其余按默认）；批准后可用 cli limit <taskId> 改。':
    'Hard limit per task: {h} h of total run time (everything else uses the defaults); after approval you can change it with cli limit <taskId>.',
  '批准后会自动逐个规划、执行：一个任务要等它依赖的任务都签收并合并后才开工；每个任务做完你签收一次。{sched}依赖关系不对，直接在反馈里说（例如"3 不依赖 2"）。请回复：':
    'Once approved, tasks are planned and run automatically one by one: a task starts only after the tasks it depends on have been signed off and merged, and you sign off each task when it is done. {sched} If the dependencies are wrong, say so in your feedback (e.g. "3 does not depend on 2"). Please reply:',
  '没有这个项目：{id}': 'No such project: {id}',
  '这个项目不是从规划开始的（没有载体任务），用 project new --file': "This project didn't start from a plan (it has no carrier task); use project new --file",
  '草案等人批': 'The draft is waiting for approval',
  '批准项目契约草案 v{version} 时的保留意见': 'Reservation when approving project plan draft v{version}',
  '项目规划器 {n} 次都没给出合规契约：{errs}': 'The project planner gave no valid contracts in {n} attempts: {errs}',

  // src/agent/spec-diff.mjs —— 【和上一版比】
  '⚠ 上一版（v{prev}）给出的任务这一版都没有了：{tasks} —— AI 这一版改判为"已经达成"。如果你没同意去掉它们：别确认达成，回复写明"还差这些"。':
    '⚠ None of the tasks from the previous version (v{prev}) are in this one: {tasks} — this time the AI judged the project "already done". If you didn\'t agree to drop them, don\'t confirm it\'s done; reply saying "these are still missing".',
  '上一版（v{prev}）判的是"已经达成"；这一版按你的反馈改为给出任务。': 'The previous version (v{prev}) judged the project "already done"; following your feedback, this version proposes tasks instead.',
  '⚠ 上一版有、这一版没有的任务：{tasks}': '⚠ Tasks in the previous version but not in this one: {tasks}',
  '⚠ 下面这些上一版的约束 / 规则，这一版里找不到一字不差的原文 —— 可能被删了，也可能只是改了措辞，请核对：':
    '⚠ The exact wording of these constraints / rules from the previous version can\'t be found in this one — they may have been removed or just reworded; please check:',
  '  - 「{task}」的{kind}：{text}': '  - {kind} of “{task}”: {text}',
  '约束': 'Constraint',
  '规则': 'Rule',
  '  - ……另有 {n} 条': '  - …and {n} more',
  '新增的任务：{tasks}': 'New tasks: {tasks}',
  '任务都在，上一版的约束与规则原文都还在（系统逐字比对，不经 AI）。': 'All tasks are still here, and the exact wording of the previous constraints and rules is all still present (compared word for word by the system, not by the AI).',
  '（系统逐字比对，不经 AI）': '(compared word for word by the system, not by the AI)',
};
